### ISSUE TITLE
SHA2 isn't suitable for passwords

### ISSUE THREAD

**Issue by paragonie-scott** [aholbreich/crypto#1]
https://github.com/aholbreich/crypto/blob/master/src/org/holbreich/crypto/examle/hash/SHA2HashingExample.java

Someone reading this code might walk away with the incorrect idea that SHA256 is fine for password storage.

[Better recommendations](https://paragonie.com/blog/2016/02/how-safely-store-password-in-2016) include: bcrypt, scrypt, and Argon2i.

**Comment by aholbreich** [comment]
Nice hint. thx

**Comment by aholbreich** [comment]
I somehowe lost the the e-mail related to this issue here. But fixed now. 
Thank you for feedback!
